### ISSUE TITLE
Yaw not working properly

### ISSUE THREAD

**Issue by gkrangan** [eschnou/ardrone-autonomy#2] opened 2013-08-28 14:33 UTC
Hello,
First of all I'd like to say, this module is awesome. I have been playing with it for the past few days and I'm impressed. Very cool, indeed.

I however am having one issue with the mission.cw() and mission.ccw(). I tried the following:
mission.takeoff()
           .forward(1)
           .cw(90)
           .ccw(90)
           .backward(1)
           .hover(1000)
           .land()

With the above sequence, I was expecting the drone would move forward by 1m, which it did. Then yaw clockwise by 90deg. The Yaw counter-clockwise by 90deg. the come backwards by 1m and then hover for 1 second and then land.

The issue that I'm having is that, it goes forward, does the cw(90), but then it hangs in there. The rest of the steps are not executed. I have to use the emergency mode to get it down, or ctrl-c out of the program, use another window to run a land program.

I also tried the go() function with Yaw(90) and it hosed up after that.

Is anyone aware of issues with the rotation functions, in this module?

Just wanted to mention that, just using the forward(), backward(), left(), right() works well.

Any help is appreciated.

Thanks.

**Comment by eschnou** [comment] 2013-08-28 15:06
Could you add an step in between the two yaws that print something to the console (use the mission.task()). I would like to know if the issue is in the cw or ccw.

If it never performs the task, it means it never 'reached' its final position. This could be due to the following setting:
https://github.com/eschnou/ardrone-autonomy/blob/master/lib/Controller.js#L10

By increasing this value, you decrease the required precision before accepting the current position as goal being achieved.

**Comment by eschnou** [comment] 2013-08-28 15:07
And thanks for the feedback :-) I'm glad to see others enjoying this library!

**Comment by gkrangan** [comment] 2013-08-28 15:28
Hi Laurent,
Thanks for the super fast response!! I will try your suggestions and update the results in this thread, when I get some time later today. BTW, from the observed behavior, it appears that the issue is probably with the CCW function. 

Also, are you recommending that I lower the EPS_ANG value? It's currently set to 0.1. What do you recommend that I lower it to?

Thanks again.

**Comment by eschnou** [comment] 2013-08-28 15:39
No, you need to increase it. Right now, the drone will assume it has reached the goal if its measured position remains within 0.1 rad (EPS_ANG) of the target during 200ms (STABLE_DELAY). So, in a windy environment, it may keep on osicllating around the target value and never stay stable longer enough to register a 'goal achieved'.

But this is just a supposition, as you said i could have a stupid bug in ccw :-)

One thing you can also do is activate the log with mission.log(path), then look at the measured yaw values. Feel free to email me the file directly.

**Comment by gkrangan** [comment] 2013-08-28 16:13
Hi Laurent,
So, when I ran the program, it took-off, went forward by 1m and then turn 90deg clockwise. I also saw the console message "completed rotating 90deg clockwise". It then hovered there (while still turned 90deg).. and after a few secs, started to twich a little bit. By then, it was getting close to some furtiture, and TV in the living room, so I ctrl-c out of the program. And used a land.js code that I have to force it to land.

I'm attaching my program (autodrone.js), the log from the mission.log() and what is seen on the console (loginfo.txt).

BTW, there is also another issue that I see at times. When I try to run a program with the ardrone-autonomy library, it gives the error on the console, that is attached in the "startup-issue.log.txt". I then have to run the example program from the node-ardrone, make it takeoff() and lan().. after that, the node-ardrone-autonomy works fine. Not sure why this starting trouble is present at times. It's not always. Sometimes, it does it consistently and other times, it does not.

Please let me know what you find in the logs.

And thanks again for all your help, looking into this.

Regards,
Ganesh

**Comment by eschnou** [comment] 2013-08-28 19:49
It seems that by replying via github, your attachments got lost. Can you ping me an email directly at laurent@eschenauer.be ? Thanks!

**Comment by gkrangan** [comment] 2013-08-29 17:06
Hi Laurent,
Just wondering if you did receive the files as attachments that I sent to your e-mail address. If you haven't received it, please let me know and I can resend them.
Thanks

**Comment by eschnou** [comment] 2013-09-01 19:42
Just did a final fix and re-tested all examples. Also added another square example using cw(90). Everything looks good to me. I'm closing this issue. Thanks again for the time and the detailed logs. Please let me know if you have any other issues.

**Closed as completed by eschnou** 2013-09-01 19:42 UTC

**Comment by gkrangan** [comment] 2013-09-01 21:28
Hi Laurent,
Thanks for the update. I will try your updated lib over the next few days and let you know.
Regards,
Ganesh

**Comment by gkrangan** [comment] 2013-09-03 14:50
Hi Laurent,
I tried your latest code with all the fixes. It's looking real good.
Thanks again.
Regards
